import { useColors } from "@/hooks/use-colors";
import { getMitraProductionStockSummary } from "@/lib/mitra-production-stock";
import { useMitraProductions } from "@/lib/mitra-productions";
import { useMitraProducts } from "@/lib/mitra-products";
import { StyleSheet, Text, View } from "react-native";

export function MitraProductionStock() {
  const colors = useColors();
  const products = useMitraProducts();
  const productions = useMitraProductions();
  const stockSummaries = getMitraProductionStockSummary(products, productions);
  const totalAvailable = stockSummaries.reduce((sum, summary) => sum + summary.availableStock, 0);

  return <View style={[styles.container, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Stok Hasil Produksi</Text><Text style={[styles.helper, { color: colors.muted }]}>Hanya Hasil Aktual dari produksi berstatus Selesai yang masuk stok.</Text><View style={[styles.totalCard, { backgroundColor: `${colors.primary}12` }]}><Text style={[styles.totalLabel, { color: colors.muted }]}>Total Stok Tersedia</Text><Text style={[styles.totalValue, { color: colors.primary }]}>{totalAvailable} unit</Text></View>{stockSummaries.length ? stockSummaries.map((summary) => <View key={summary.productId} style={[styles.productCard, { borderTopColor: colors.border }]}><View style={styles.productHeader}><View style={styles.productCopy}><Text style={[styles.productName, { color: colors.foreground }]}>{summary.productName}</Text><Text style={[styles.productMeta, { color: colors.muted }]}>Produk dari Master Produk</Text></View><Text style={[styles.available, { color: colors.primary }]}>{summary.availableStock} unit</Text></View><View style={styles.detailRow}><StockDetail label="Stok Masuk" value={`${summary.stockIn} unit`} colors={colors} /><StockDetail label="Stok Tersedia" value={`${summary.availableStock} unit`} colors={colors} /></View><Text style={[styles.historyTitle, { color: colors.foreground }]}>Riwayat Stok</Text>{summary.history.map((production) => <View key={production.id} style={[styles.historyRow, { borderTopColor: colors.border }]}><Text style={[styles.historyDate, { color: colors.muted }]}>{production.productionDate}</Text><Text style={[styles.historyValue, { color: colors.foreground }]}>+{production.actualQuantity ?? 0} unit</Text></View>)}</View>) : <Text style={[styles.empty, { color: colors.muted }]}>Belum ada Hasil Produksi selesai yang dapat masuk stok.</Text>}</View>;
}

function StockDetail({ label, value, colors }: { label: string; value: string; colors: ReturnType<typeof useColors> }) { return <View style={styles.detail}><Text style={[styles.detailLabel, { color: colors.muted }]}>{label}</Text><Text style={[styles.detailValue, { color: colors.foreground }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ container: { borderWidth: 1, borderRadius: 19, padding: 15, marginTop: 14, marginBottom: 14 }, title: { fontSize: 19, fontWeight: "800" }, helper: { fontSize: 12, lineHeight: 18, marginTop: 5 }, totalCard: { borderRadius: 13, padding: 13, marginTop: 13 }, totalLabel: { fontSize: 11 }, totalValue: { fontSize: 23, fontWeight: "800", marginTop: 3 }, productCard: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 13, marginTop: 15 }, productHeader: { flexDirection: "row", alignItems: "center" }, productCopy: { flex: 1 }, productName: { fontSize: 14, fontWeight: "800" }, productMeta: { fontSize: 10, marginTop: 3 }, available: { fontSize: 15, fontWeight: "800" }, detailRow: { flexDirection: "row", gap: 9, marginTop: 12 }, detail: { flex: 1, borderRadius: 10, padding: 9, backgroundColor: "rgba(127, 127, 127, 0.08)" }, detailLabel: { fontSize: 10 }, detailValue: { fontSize: 12, fontWeight: "800", marginTop: 3 }, historyTitle: { fontSize: 12, fontWeight: "800", marginTop: 14, marginBottom: 5 }, historyRow: { flexDirection: "row", justifyContent: "space-between", borderTopWidth: StyleSheet.hairlineWidth, paddingVertical: 8 }, historyDate: { fontSize: 11 }, historyValue: { fontSize: 11, fontWeight: "800" }, empty: { fontSize: 12, lineHeight: 18, marginTop: 16 },
});
